/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.gradebook.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.training.gradebook.model.Krishna;
import com.liferay.training.gradebook.model.KrishnaModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Krishna service. Represents a row in the &quot;Gradebook_Krishna&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>KrishnaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KrishnaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KrishnaImpl
 * @generated
 */
@JSON(strict = true)
public class KrishnaModelImpl
	extends BaseModelImpl<Krishna> implements KrishnaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a krishna model instance should use the <code>Krishna</code> interface instead.
	 */
	public static final String TABLE_NAME = "Gradebook_Krishna";

	public static final Object[][] TABLE_COLUMNS = {
		{"name", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"userId", Types.INTEGER}, {"krishnaId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("krishnaId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Gradebook_Krishna (name VARCHAR(75) null,description VARCHAR(75) null,userId INTEGER not null primary key,krishnaId LONG)";

	public static final String TABLE_SQL_DROP = "drop table Gradebook_Krishna";

	public static final String ORDER_BY_JPQL = " ORDER BY krishna.userId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Gradebook_Krishna.userId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESCRIPTION_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public KrishnaModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _userId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Krishna.class;
	}

	@Override
	public String getModelClassName() {
		return Krishna.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Krishna, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Krishna, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Krishna, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Krishna)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Krishna, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Krishna, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Krishna)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Krishna, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Krishna, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Krishna, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Krishna, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Krishna, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Krishna, Object>>();
		Map<String, BiConsumer<Krishna, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Krishna, ?>>();

		attributeGetterFunctions.put("name", Krishna::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Krishna, String>)Krishna::setName);
		attributeGetterFunctions.put("description", Krishna::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<Krishna, String>)Krishna::setDescription);
		attributeGetterFunctions.put("userId", Krishna::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Krishna, Integer>)Krishna::setUserId);
		attributeGetterFunctions.put("krishnaId", Krishna::getKrishnaId);
		attributeSetterBiConsumers.put(
			"krishnaId", (BiConsumer<Krishna, Long>)Krishna::setKrishnaId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDescription() {
		return getColumnOriginalValue("description");
	}

	@JSON
	@Override
	public int getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(int userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalUserId() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public long getKrishnaId() {
		return _krishnaId;
	}

	@Override
	public void setKrishnaId(long krishnaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_krishnaId = krishnaId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Krishna toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Krishna>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KrishnaImpl krishnaImpl = new KrishnaImpl();

		krishnaImpl.setName(getName());
		krishnaImpl.setDescription(getDescription());
		krishnaImpl.setUserId(getUserId());
		krishnaImpl.setKrishnaId(getKrishnaId());

		krishnaImpl.resetOriginalValues();

		return krishnaImpl;
	}

	@Override
	public Krishna cloneWithOriginalValues() {
		KrishnaImpl krishnaImpl = new KrishnaImpl();

		krishnaImpl.setName(this.<String>getColumnOriginalValue("name"));
		krishnaImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		krishnaImpl.setUserId(this.<Integer>getColumnOriginalValue("userId"));
		krishnaImpl.setKrishnaId(
			this.<Long>getColumnOriginalValue("krishnaId"));

		return krishnaImpl;
	}

	@Override
	public int compareTo(Krishna krishna) {
		int value = 0;

		if (getUserId() < krishna.getUserId()) {
			value = -1;
		}
		else if (getUserId() > krishna.getUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Krishna)) {
			return false;
		}

		Krishna krishna = (Krishna)object;

		int primaryKey = krishna.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Krishna> toCacheModel() {
		KrishnaCacheModel krishnaCacheModel = new KrishnaCacheModel();

		krishnaCacheModel.name = getName();

		String name = krishnaCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			krishnaCacheModel.name = null;
		}

		krishnaCacheModel.description = getDescription();

		String description = krishnaCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			krishnaCacheModel.description = null;
		}

		krishnaCacheModel.userId = getUserId();

		krishnaCacheModel.krishnaId = getKrishnaId();

		return krishnaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Krishna, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Krishna, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Krishna, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Krishna)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Krishna>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Krishna.class, ModelWrapper.class);

	}

	private String _name;
	private String _description;
	private int _userId;
	private long _krishnaId;

	public <T> T getColumnValue(String columnName) {
		Function<Krishna, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Krishna)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("krishnaId", _krishnaId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("name", 1L);

		columnBitmasks.put("description", 2L);

		columnBitmasks.put("userId", 4L);

		columnBitmasks.put("krishnaId", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Krishna _escapedModel;

}