/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.gradebook.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Krishna service. Represents a row in the &quot;Gradebook_Krishna&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.gradebook.model.impl.KrishnaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.gradebook.model.impl.KrishnaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Krishna
 * @generated
 */
@ProviderType
public interface KrishnaModel extends BaseModel<Krishna> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a krishna model instance should use the {@link Krishna} interface instead.
	 */

	/**
	 * Returns the primary key of this krishna.
	 *
	 * @return the primary key of this krishna
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this krishna.
	 *
	 * @param primaryKey the primary key of this krishna
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the name of this krishna.
	 *
	 * @return the name of this krishna
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this krishna.
	 *
	 * @param name the name of this krishna
	 */
	public void setName(String name);

	/**
	 * Returns the description of this krishna.
	 *
	 * @return the description of this krishna
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this krishna.
	 *
	 * @param description the description of this krishna
	 */
	public void setDescription(String description);

	/**
	 * Returns the user ID of this krishna.
	 *
	 * @return the user ID of this krishna
	 */
	public int getUserId();

	/**
	 * Sets the user ID of this krishna.
	 *
	 * @param userId the user ID of this krishna
	 */
	public void setUserId(int userId);

	/**
	 * Returns the krishna ID of this krishna.
	 *
	 * @return the krishna ID of this krishna
	 */
	public long getKrishnaId();

	/**
	 * Sets the krishna ID of this krishna.
	 *
	 * @param krishnaId the krishna ID of this krishna
	 */
	public void setKrishnaId(long krishnaId);

	@Override
	public Krishna cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}